### ISSUE TITLE
Add `connectTimeout` option

### ISSUE THREAD

**Issue by szmarczak** [delvedor/hpagent#29]
https://github.com/delvedor/hpagent/blob/ac3b00dcb12f39e3ae4bd81fa953759e1a40f1c6/index.js#L62-L70

Currently there is no timeout set.

**Comment by korniychuk** [comment]
Here is the solution: 
![Ankor 2021-11-01 at 20 43 15@2x](https://user-images.githubusercontent.com/11693557/139724124-a3e5de18-ad04-4e2a-a9be-3f2f3a8805f0.png)
