### ISSUE TITLE
Allow http_proxy, https_proxy and no_proxy env variables

### ISSUE THREAD

**Issue by javi11** [delvedor/hpagent#35]
What do you think on allowing on this module the standard proxy environment variables of http_proxy, https_proxy, HTTP_PROXY, HTTPS_PROXY and no_proxy.

I can do a pull request if you feel that is useful for the module :)

**Comment by mbargiel** [comment]
Did you take a look at [proxy-from-env](https://www.npmjs.com/package/proxy-from-env) to implement this in your own code? It's pretty straightforward to use.

I think it would be preferable if this simple, lightweight library remained just that way - a simple, lightweight library. I could definitely see another package wrapping this with some factory functionality that supports env-var based proxy resolution then instantiates the right agent class for a given target URL.

**Comment by delvedor** [comment]
Closed in https://github.com/delvedor/hpagent/pull/36#pullrequestreview-970391689.
