### ISSUE TITLE
Proxy username/password get percent-encoded because of `new URL` when they shouldn't

### ISSUE THREAD

**Issue by Ricardonacif** [delvedor/hpagent#39]
On the example below, because of the internal use of `new URL` to parse the proxy url, the username and password get [percent-encoded](https://nodejs.org/api/url.html#percent-encoding-in-urls). This is ideal for URLs, but when we are parsing for username and password for proxy auth, that breaks the strings because the username is converted to `username_with_%3D`:

```
new HttpsProxyAgent({
          proxy: 'http://username_with_=:password@33.206.125.154:8888',
        });```
```

I have used some proxy providers where there are `=` chars on the username and for instance on chrome the proxies work fine, but not on hpagent. Should we forcely decoded that on username/password?

**Comment by gaetanlegac** [comment]
I have the same issue, getting a `422` error when the password contains a `;`.
