### ISSUE TITLE
Feature request: support ca and rejectUnauthorized for HTTPS proxy server

### ISSUE THREAD

**Issue by mbargiel** [delvedor/hpagent#69]
The `ca` and `rejectUnauthorized` properties from the request options are correctly passed to the upstream HTTPS endpoints but it's currently not possible to set those for the proxy server itself when sending the HTTP CONNECT request. This means it's impossible to use this implementation with an HTTPS proxy server unless that server uses a certificate from a well-known certificate authority.

I can think of two simple options to support these options:
1. Pass the `ca` and `rejectUnauthorized` properties from the `createConnection` `options` parameter to the `https.request` function, through the `requestOptions`.
2. Support additional, non-standard properties to allow separately configuring the proxy server connection and the upstream connection. Ideas: 
2.1. `options.proxyCa` and `options.proxyRejectUnauthorized`
2.2. `options.proxy.ca` and `options.proxy.rejectUnauthorized`
2.3. `options.proxyAgentOptions.ca` and `options.proxyAgentOptions.rejectUnauthorized`
3. Support passing an agent for the proxy connection: `options.proxyAgent`

Personally, I dislike option 1 because it's inflexible. Any other option seems good to me.

I can provide a PR for this, based on which one is your preference.

**Comment by ckcr4lyf** [comment]
Btw, for the time being you could also use `NODE_EXTRA_CA_CERTS` option and pass your proxy cert to it, which will make the underlying implementation trust it. 

But I like your idea number 2.

**Comment by delvedor** [comment]
Hello! You are right, there is no option to do what you need.
I agree tho that you can easily solve this via the [`NODE_EXTRA_CA_CERTS`](https://nodejs.org/api/cli.html#node_extra_ca_certsfile) env variable, which should be the best way to address this issue.
Does this work for you?

**Comment by mbargiel** [comment]
Hi @delvedor ! Thanks for the suggestion. I already knew about this option but it's unfortunately not something that should ever be used in production because it makes your code vulnerable to Man-in-the-Middle attacks for every request. For instance, if I want to connect to a proxy without validating its certificate (or rather, with a custom CA vertificate), I most certainly do not want to disable certificate validation for the upstream call itself and all unproxied calls!

**Comment by ckcr4lyf** [comment]
It will not disable validation (that option it TLS_REJECT_UNAUTHORIZED), rather it will trust a custom certificate. As long as you make sure the cert is only for that specific domain, I think it's an appropriate use case.

**Comment by mbargiel** [comment]
> It will not disable validation (that option it TLS_REJECT_UNAUTHORIZED), rather it will trust a custom certificate. As long as you make sure the cert is only for that specific domain, I think it's an appropriate use case.

Oh geez yes, I read too fast :sweat_smile:  My bad!

You're right, it's an option under some circumstances but not mine. It assumes we know the extra certs upfront because it's only heeded by Node at startup. If you set it later, from within the process, it does nothing.

**Comment by ckcr4lyf** [comment]
That is true, yeah. I can certainly imagine a use case wherein you provision a proxy with a self signed cert generated after the node process to be using it starts, so a way to pass in a proxy cert at runtime would be beneficial.

**Comment by delvedor** [comment]
https://github.com/delvedor/hpagent/blob/cc90c2b60a0b946574993d5598d93229ce452f72/index.js#L17-L26

**Comment by mbargiel** [comment]
Gotcha! 

One more thing: as I was getting a PR prepared, I noticed the tests had _a lot_ of duplication, and in some cases, there were tests missing in some combinations of http-http, http-https, etc. I have a branch where I played with reducing the duplication by parameterizing tests and I got that working pretty simply without losing any clarity. Would you be interested in seeing this in a PR?

**Comment by mbargiel** [comment]
Another question: I'm not certain how to validate my implementation. I would normally use a mocking library like `sinon` to detect that e.g. `http.request` was called with the right custom options and without overriding the internal options defaults but you're not using any in this project. I'm not sure if there's an other client-side event I could rely on, before or while issuing the remote connection, to detect whether custom proxy request options were correctly passed. Do have any suggestion?

For now, what I could do was with `request` and `connect` events on the server and proxy sides to check the headers that had been passed, but I'd like to validate actual connection-related options.

**Comment by arossert** [comment]
Any estimation of when this is going to be implemented?

**Comment by mbargiel** [comment]
@arossert I don't know, I opened a PR for this 3 months ago but it seems that @delvedor didn't see it, didn't have time or might have forgotten about it 😅 I'm also interested in getting this landed before we can use it in production code.

**Comment by delvedor** [comment]
Closed in #72.
